package application;

public enum ErrorApplication {
    EMPTY_FIELD,
    NOT_REGISTERED,
    WRONG_PASSWORD,
    ADD_NEGATIVE_CREDITS,
    ADD_ZERO_CREDITS,
    NOT_LOGGED,
    ZERO_CREDITS,
    EBIKE_IN_USE,
    EBIKE_LOW_BATTERY,
    NOT_CONNECTED,
    SAME_USERNAME

}
