services:
  userRepository:
    image: eclipse-temurin:21-jdk
    container_name: UserRepository
    volumes:
      - ./UserRepository/build/libs:/app
    working_dir: /app
    command: [ "java", "-jar", "userRepository.jar" ]
    ports:
      - "3001:3001"
    networks:
      - custom-network
    environment:
      - SERVER_PORT=3001

  ebikeRepository:
    image: eclipse-temurin:21-jdk
    container_name: EBikeRepository
    volumes:
      - ./EBikeRepository/build/libs:/app
    working_dir: /app
    command: [ "java", "-jar", "eBikeRepository.jar" ]
    ports:
      - "3002:3002"
    networks:
      - custom-network
    environment:
      - SERVER_PORT=3002

  GatewayRepository:
    image: eclipse-temurin:21-jdk
    container_name: GatewayRepository
    volumes:
      - ./GatewayRepository/build/libs:/app
    working_dir: /app
    command: [ "java", "-jar", "gatewayRepository.jar" ]
    ports:
      - "3000:3000"
    networks:
      - custom-network
    environment:
      - SERVER_PORT=3000

  prometheus:
    image: prom/prometheus:latest  # Usa l'immagine ufficiale di Prometheus
    container_name: Prometheus
    ports:
      - "9090:9090"  # Porta per l'interfaccia web di Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta il file di configurazione
    networks:
      - custom-network
    environment:
      - SERVER_PORT=9090

networks:
  custom-network:
    driver: bridge
