services:

  userRepository:
    image: eclipse-temurin:21-jdk
    container_name: UserRepository
    volumes:
      - ./UserRepository/build/libs:/app
    working_dir: /app
    command: [ "java", "-jar", "userRepository.jar" ]
    ports:
      - "3001:3001"
    networks:
      - custom-network
    environment:
      - SERVER_PORT=3001

  GatewayRepository:
    image: eclipse-temurin:21-jdk
    container_name: Gateway-Repository
    volumes:
      - ./GatewayRepository/build/libs:/app
    working_dir: /app
    command: [ "java", "-jar", "gatewayRepository.jar" ]
    ports:
      - "3000:3000"
    networks:
      - custom-network
    environment:
      - SERVER_PORT=3000

networks:
  custom-network:
    driver: bridge
