#FROM ubuntu:latest
#LABEL authors="manuelbuizo"
#
## Usa l'immagine base di OpenJDK
#FROM eclipse-temurin:21-jdk
#
## Imposta la directory di lavoro nel container
#WORKDIR /UserRepository
#
## Copia il file JAR nell'immagine Docker
#COPY build/libs/userRepository.jar app.jar
#
## Esporre la porta su cui l'applicazione ascolta
#EXPOSE 3000
#
## Specifica il comando per eseguire il file JAR
#CMD ["java", "-jar", "app.jar"]
#
