# Configurazione del servizio
service.port=3001

user.total=3

# Utenti predefiniti
user1.username=manuel
user1.password=1234
user1.credits=500

user2.username=marco
user2.password=1234
user2.credits=1500

user3.username=marta
user3.password=1234
user3.credits=1000